// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID          uuid.UUID      `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	TotalAmount int32          `json:"total_amount"`
	DateEvent   sql.NullTime   `json:"date_event"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	CanEdit     bool           `json:"can_edit"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	IsActive    bool           `json:"is_active"`
}

type EventMemberDetail struct {
	ID           uuid.UUID      `json:"id"`
	EventID      uuid.UUID      `json:"event_id"`
	UserID       uuid.UUID      `json:"user_id"`
	Bill         sql.NullInt32  `json:"bill"`
	Paid         sql.NullInt32  `json:"paid"`
	Compensation sql.NullInt32  `json:"compensation"`
	Notes        sql.NullString `json:"notes"`
	Done         bool           `json:"done"`
}

type EventPurchaseDetail struct {
	ID         uuid.UUID    `json:"id"`
	EventID    uuid.UUID    `json:"event_id"`
	Name       string       `json:"name"`
	Qty        int32        `json:"qty"`
	EachPrice  int32        `json:"each_price"`
	TotalPrice int32        `json:"total_price"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type PaymentHistory struct {
	ID                   uuid.UUID      `json:"id"`
	EventMemberDetailsID uuid.UUID      `json:"event_member_details_id"`
	FromUserID           uuid.UUID      `json:"from_user_id"`
	ToUserID             uuid.UUID      `json:"to_user_id"`
	Nominal              int32          `json:"nominal"`
	Description          sql.NullString `json:"description"`
	CreatedAt            time.Time      `json:"created_at"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Username  sql.NullString `json:"username"`
	Email     string         `json:"email"`
	CreatedAt time.Time      `json:"created_at"`
}
