// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: event_member_details.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addMemberDetails = `-- name: AddMemberDetails :one
INSERT INTO event_member_details
(event_id, user_id, bill, paid, compensation, notes, done)
VALUES(
  $1, $2, $3, $4, $5, $6 ,$7
)
RETURNING id, event_id, user_id, bill, paid, compensation, notes, done
`

type AddMemberDetailsParams struct {
	EventID      uuid.UUID      `json:"event_id"`
	UserID       uuid.UUID      `json:"user_id"`
	Bill         sql.NullInt32  `json:"bill"`
	Paid         sql.NullInt32  `json:"paid"`
	Compensation sql.NullInt32  `json:"compensation"`
	Notes        sql.NullString `json:"notes"`
	Done         bool           `json:"done"`
}

func (q *Queries) AddMemberDetails(ctx context.Context, arg AddMemberDetailsParams) (EventMemberDetail, error) {
	row := q.db.QueryRowContext(ctx, addMemberDetails,
		arg.EventID,
		arg.UserID,
		arg.Bill,
		arg.Paid,
		arg.Compensation,
		arg.Notes,
		arg.Done,
	)
	var i EventMemberDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Bill,
		&i.Paid,
		&i.Compensation,
		&i.Notes,
		&i.Done,
	)
	return i, err
}

const getMemberDetails = `-- name: GetMemberDetails :one
SELECT 
  id, 
  event_id, 
  user_id, 
  bill, 
  paid, 
  compensation, 
  notes, 
  done
FROM event_member_details
WHERE id=$1
`

func (q *Queries) GetMemberDetails(ctx context.Context, id uuid.UUID) (EventMemberDetail, error) {
	row := q.db.QueryRowContext(ctx, getMemberDetails, id)
	var i EventMemberDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Bill,
		&i.Paid,
		&i.Compensation,
		&i.Notes,
		&i.Done,
	)
	return i, err
}

const listMemberDetails = `-- name: ListMemberDetails :many
SELECT 
  id, 
  event_id, 
  user_id, 
  bill, 
  paid, 
  compensation, 
  notes, 
  done
FROM event_member_details
WHERE event_id=$1
`

func (q *Queries) ListMemberDetails(ctx context.Context, eventID uuid.UUID) ([]EventMemberDetail, error) {
	rows, err := q.db.QueryContext(ctx, listMemberDetails, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventMemberDetail{}
	for rows.Next() {
		var i EventMemberDetail
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Bill,
			&i.Paid,
			&i.Compensation,
			&i.Notes,
			&i.Done,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberDetails = `-- name: UpdateMemberDetails :one
UPDATE event_member_details 
SET 
  bill = $2, 
  paid = $3, 
  compensation =$4, 
  notes=$5, 
  done=$6
WHERE id = $1
RETURNING id, event_id, user_id, bill, paid, compensation, notes, done
`

type UpdateMemberDetailsParams struct {
	ID           uuid.UUID      `json:"id"`
	Bill         sql.NullInt32  `json:"bill"`
	Paid         sql.NullInt32  `json:"paid"`
	Compensation sql.NullInt32  `json:"compensation"`
	Notes        sql.NullString `json:"notes"`
	Done         bool           `json:"done"`
}

func (q *Queries) UpdateMemberDetails(ctx context.Context, arg UpdateMemberDetailsParams) (EventMemberDetail, error) {
	row := q.db.QueryRowContext(ctx, updateMemberDetails,
		arg.ID,
		arg.Bill,
		arg.Paid,
		arg.Compensation,
		arg.Notes,
		arg.Done,
	)
	var i EventMemberDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Bill,
		&i.Paid,
		&i.Compensation,
		&i.Notes,
		&i.Done,
	)
	return i, err
}
