// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Event struct {
	ID          int32          `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
	Status      sql.NullString `json:"status"`
	TotalAmount sql.NullInt32  `json:"total_amount"`
	DateEvent   sql.NullTime   `json:"date_event"`
	CreatedBy   sql.NullInt32  `json:"created_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type EventMemberDetail struct {
	ID           int32          `json:"id"`
	EventID      sql.NullInt32  `json:"event_id"`
	UserID       sql.NullInt32  `json:"user_id"`
	Bill         sql.NullInt32  `json:"bill"`
	Paid         sql.NullInt32  `json:"paid"`
	Compensation sql.NullInt32  `json:"compensation"`
	Notes        sql.NullString `json:"notes"`
	Done         sql.NullBool   `json:"done"`
}

type EventPurchaseDetail struct {
	ID         int32          `json:"id"`
	EventID    sql.NullInt32  `json:"event_id"`
	Name       sql.NullString `json:"name"`
	Qty        sql.NullInt32  `json:"qty"`
	EachPrice  sql.NullInt32  `json:"each_price"`
	TotalPrice sql.NullInt32  `json:"total_price"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type PaymentHistory struct {
	ID                   int32          `json:"id"`
	EventMemberDetailsID sql.NullInt32  `json:"event_member_details_id"`
	ToUserID             sql.NullInt32  `json:"to_user_id"`
	Nominal              sql.NullInt32  `json:"nominal"`
	Description          sql.NullString `json:"description"`
	CreatedAt            sql.NullTime   `json:"created_at"`
}

type User struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	Title     sql.NullString `json:"title"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
