// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment_history.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addPaymentHistory = `-- name: AddPaymentHistory :one
INSERT INTO payment_history
( event_member_details_id, to_user_id, nominal, description, created_at)
VALUES( $1, $2, $3, $4, $5)
RETURNING id, event_member_details_id, to_user_id, nominal, description, created_at
`

type AddPaymentHistoryParams struct {
	EventMemberDetailsID uuid.UUID      `json:"event_member_details_id"`
	ToUserID             uuid.UUID      `json:"to_user_id"`
	Nominal              int32          `json:"nominal"`
	Description          sql.NullString `json:"description"`
	CreatedAt            time.Time      `json:"created_at"`
}

func (q *Queries) AddPaymentHistory(ctx context.Context, arg AddPaymentHistoryParams) (PaymentHistory, error) {
	row := q.db.QueryRowContext(ctx, addPaymentHistory,
		arg.EventMemberDetailsID,
		arg.ToUserID,
		arg.Nominal,
		arg.Description,
		arg.CreatedAt,
	)
	var i PaymentHistory
	err := row.Scan(
		&i.ID,
		&i.EventMemberDetailsID,
		&i.ToUserID,
		&i.Nominal,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentHistory = `-- name: ListPaymentHistory :many
SELECT 
  ph.to_user_id,
  ph.nominal, 
  ph.description, 
  ph.created_at 
FROM payment_history ph 
JOIN event_member_details emd on  ph.event_member_details_id = emd.id 
JOIN events e on emd.event_id = e.id  
WHERE e.id=$1
`

type ListPaymentHistoryRow struct {
	ToUserID    uuid.UUID      `json:"to_user_id"`
	Nominal     int32          `json:"nominal"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) ListPaymentHistory(ctx context.Context, id uuid.UUID) ([]ListPaymentHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentHistory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentHistoryRow{}
	for rows.Next() {
		var i ListPaymentHistoryRow
		if err := rows.Scan(
			&i.ToUserID,
			&i.Nominal,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentHistory = `-- name: UpdatePaymentHistory :one
UPDATE payment_history
SET 
  event_member_details_id= $2, 
  to_user_id=$3, 
  nominal=$4,
  description= $5, 
  created_at= $6
WHERE id=$1
RETURNING id, event_member_details_id, to_user_id, nominal, description, created_at
`

type UpdatePaymentHistoryParams struct {
	ID                   uuid.UUID      `json:"id"`
	EventMemberDetailsID uuid.UUID      `json:"event_member_details_id"`
	ToUserID             uuid.UUID      `json:"to_user_id"`
	Nominal              int32          `json:"nominal"`
	Description          sql.NullString `json:"description"`
	CreatedAt            time.Time      `json:"created_at"`
}

func (q *Queries) UpdatePaymentHistory(ctx context.Context, arg UpdatePaymentHistoryParams) (PaymentHistory, error) {
	row := q.db.QueryRowContext(ctx, updatePaymentHistory,
		arg.ID,
		arg.EventMemberDetailsID,
		arg.ToUserID,
		arg.Nominal,
		arg.Description,
		arg.CreatedAt,
	)
	var i PaymentHistory
	err := row.Scan(
		&i.ID,
		&i.EventMemberDetailsID,
		&i.ToUserID,
		&i.Nominal,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
